name: '🧹 Cleanup'
description: 'Clean working directory on self-hosted runners'

runs:
  using: composite
  steps:
    - id: step-1
      name: '🧹 Clean working directory'
      shell: bash
      # TODO: evaluate rm -rf "${{ github.workspace }}"
      run: |
        echo "This is the action from the ${{ inputs.repository }} repository..."
        rm -rf ./*
